In [2]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int32')

In [10]:
b.ndim

2

In [12]:
print(type(b))

<class 'numpy.ndarray'>


In [13]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
c= range(1000)
c

range(0, 1000)

In [23]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [36]:
np.full((2,2),2.2, dtype=np.int)

array([[2, 2],
       [2, 2]])

In [38]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
v=np.array([1,2,3])
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [43]:
np.random.random([3,3])

array([[0.77179294, 0.73924127, 0.34981825],
       [0.81550071, 0.54266557, 0.50277627],
       [0.18563708, 0.71066327, 0.54149465]])

In [47]:
#between 1 to 50 split it 100 parts equally
a=np.linspace(1,50,100)
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [49]:
a.itemsize

8

In [54]:
b=np.arange(18).reshape(2,3,3)
b


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [61]:
b.shape

(2, 3, 3)

In [64]:
a=np.array([2,4,6,10,3,4,5])
a

array([ 2,  4,  6, 10,  3,  4,  5])

In [66]:
a[0]

2

In [68]:
a[2]

6

In [70]:
a[[2,4,6]]

array([6, 3, 5])

In [72]:
 a[0::2]

array([2, 6, 3, 5])

In [77]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a[2,2]

9

In [81]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [84]:
a[(a>2)&(a>5)]

array([6, 7, 8, 9])

In [86]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#if we dont put copy fuction and when we assigh value both will get changed(a,b)
b=a.copy()

In [95]:
b[0]=11

In [97]:
np.shares_memory(a,b)

False

In [100]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
#we arebtransposing that means all row will become column
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [106]:
b=np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [108]:
a==b

array([[False, False, False],
       [False, False, False]])

In [110]:
#vertical stack horizontal stack hstack
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [113]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# sine of array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [118]:
np.sum(a)

45